### ISSUE TITLE
RunnerUp 2.0.0 Alpha3

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#753]
The third Alpha release of RunnerUp 2.0

This identifies as a separate application and can be used in parallel with the Play application.
For details see:
https://htmlpreview.github.io/?https://github.com/jonasoreland/runnerup/blob/master/app/assets/changes.html

https://github.com/jonasoreland/runnerup/releases

**Comment by gerhardol** [comment]
Plan to release a new build in some time with #762

**Comment by poQjdH35zNNQ** [comment]
Hey @gerhardol 

So as promessed I tried RunnerUp 2.0.0.3 on my phone (Android 9) and here is my feedback.

First, it recorded both my location and my heart rate (with a bluetooth chest strap) perfectly, and I had no problem during the training.

Then, there are two things that don't work when I open the saved workout :
- the app crashes when I click on the map (either on the red road or on a yellow pin)
- the heart rate printed in the last column of the "laps" tab is wrong (the same wrong value (120) is repeated a lot). It doesn't match what is shown on the "graph" tab, which is correct.

Everything else seems good.

Now, what I missed and would like to see added in feature releases :

- keep the screen on : it would be useful while cycling to always see current speed, current heart rate and map :
  - current speed and current heart rate => make them bigger so we can easily read them
  - map => show the map during the workout
- choose between pace and speed
- and finally (sorry to insist :D ) record the heart rate during an indoor training. I understand that recording a workout is tied to the GPS, but in the settings when we configure a bluetooth device we can see our heart rate on a graph, so I really see no reason why it can't record it and then later display it on a graph.

Thanks for you work, and I'm here is you need more info to fix the 2 bugs

**Comment by gerhardol** [comment]
Will look at the issues. No activities with HR right now.

Keep screen on:
I suggest that you use a separate app for that. I use Tasker. A quick search, this seem to work for me:
https://play.google.com/store/apps/details?id=com.synetics.stay.alive&hl=sv&rdid=com.synetics.stay.alive

Pace/Speed:
I have considered that but RU is very limited for cycling use anyway, many other changes would be needed for the app to be really useful for live reporting. Patches are accepted.

No GPS recording:
I can support in implementing that, but I do not think I have time to do this myself.

**Comment by craftyguy** [comment]
Any chance we could get an Alpha4 to test? (I'm specifically interested in #766 since it is causing lots of problems with activities being recorded as 'running' when they are not)

**Comment by gerhardol** [comment]
Alpha4 is planned, I am working with some ANT+ corrections and the issues reported above too.

**Comment by gerhardol** [comment]
@poQjdH35zNNQ 
map crash:
I could create it once with a release build but not with a debug build. (Switching builds requires aclean installation, that is adding to the time to debug that.) The logcat indicated that the error was internal to MapBox, so I will update the package (to the latest not requiring too many changes).

lap hr:
That works for me.

**Comment by poQjdH35zNNQ** [comment]
Well that's weird, I recorded 4 more trainings since then, and HR lap is wrong for all of them.
To be more precise, it can't go higher than 120 : when my HR is above 120, it says 120. But when it is below 120 it is correct.

**Comment by gerhardol** [comment]
2.0.0.4 released. Open new issues if you see something there

@poQjdH35zNNQ 
For average HR: OK for me also with over 120bpm
Any other specifics, like do you use autolap only, workout etc

**Comment by craftyguy** [comment]
FWIW, I also see the HR maxing out at 120 BPM in the app, but when exporting as tcx it seems to output the right BPM.

**Comment by poQjdH35zNNQ** [comment]
@gerhardol no specific setting, a "simple" workout, running or cycling, with 1km autolap.

I just discovered that I could edit a training and recalculate its data afterwards, and when I do that it calculates the right average lap HR.

Map crashes are fixed in 2.0.0.4, thanks !

**Comment by gerhardol** [comment]
LapHR:
What HR strap do you have, what phone?
Do you have loss of HR periodically?

The algorithms for "original" calculations and recompute are slightly different, all data is not available at recompute. Some HR sensors reports 0 occasionally (as a heart beat? not being ironic here). 
Both algorithms do not handle loss of hr well though, it is expected that all time GPS is updated, that HR is available too. But there is no reason to see max 120.

**Comment by poQjdH35zNNQ** [comment]
Pixel 3 & Garmin HRM-Dual
No sign of loss, HeartRateBpm fields are filled in in the TCX files.

There must be a reason since we are at least two to have this problem :-)

**Comment by craftyguy** [comment]
I have a Nexus 5X with LineageOS 15.1. HRM is a Wahoo TICKR.

> Do you have loss of HR periodically?
I do, actually, but it seems I also lose GPS logging periodically at the same time as I lose HRM logging in my TCX files that Runnerup outputs... This may be an unrelated problem since @poQjdH35zNNQ doesn't lose HR periodically and is still experiencing the 120bpm issue in the app.

**Comment by moobyfr** [comment]
I also got the 120 bpm issue with runnerup (only on display, not on exported date nor on the data in the history). Didn't make exercices lately with runnerup to reproduce it again.

**Comment by gerhardol** [comment]
Is it only lap HR for current activity 120, are all other HR OK?
(Is Current HR and Interval HR as well as History detail lap HR OK?)

>  do, actually, but it seems I also lose GPS logging periodically at the same time as I lose HRM logging 

GPS provide the "ticks" so no HR will be logged when GPS appears.
I do not believe the TICKr reports 0.

**Comment by craftyguy** [comment]
> GPS provide the "ticks" so no HR will be logged when GPS appears.
I do not believe the TICKr reports 0.

So if I understand you correctly, this is a problem with GPS dropping out, resulting in nothing being logged?

**Comment by gerhardol** [comment]
>So if I understand you correctly, this is a problem with GPS dropping out, resulting in nothing being logged?
> Edit: "this is a problem" meaning, the issue I mentioned earlier about periodically losing HR and GPS.. not the issue with 120 bpm :)

Correct
Similar to lack of indoor recording
